### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by lilysandstrom** [meghalithic/microporella#2]
The readme text explains the points on the figure showing landmark points 1 - 22 (overlayed on an image from Di Martino et al., 2023): 
Autozooid (yellow shading, white lines):
 Shape:
  zooid height: 16-9
  operculum (pink shading): height between 6, 7, 8
  operculum base length (pink shading): 7-8
  proximal width: 22-10
  distal width: 17-15
  proximal side length: average between 22-19 and 10-13
  distal side length: average between 19-17 and 13-15
  zooid width: 19-13

Ascopore (lime green shading, black lines):
 Shape: area
 Position to operculum: proximal-distal position
  position to operculum (right side): 1-7
  position to operculum (left side): 1-8
 Position to side wall: relative position
  position to right side wall: 19-1
  position to left side wall: 13-1

Avicularia (purple shading, grey lines):
 Shape:
  length: 2-5
  height: 3-4
  area
 Position to operculum: proximal-distal position
  position to operculum (left side): 4-8
  position to operculum (right side): 4-7
 Position to side wall: relative position
  position to left wall: 13-5
  position to right wall: 19-2

So from what I can gather, the points 1-22 in the Readme figure are as follows:
<ins>Autozooid landmarks on Readme image</ins> :
1: marks the center of the ascopore
2: If "position to right wall: 19-2" then 2 marks the avivulariums edge to the zooids "right" (from the image orientation, but the zooids left if proximal end is "up"?) In cases where there are two avicularia, then maybe left/right markers are easier if you want to compare the form of the two avicularia than medial/lateral side markers? In that case 2 on the readme image is the medial edge of the avicularium. Maybe you want to be able to know if the avicularium is on the left or right side of the zooid in addition to the length and width? If the length between point 2 and 5 is what is important, then maybe it is not as important to be consistent with whether point 2 or point 5 is the left side? Maybe you want to be able to know if the avicularium is on the left or right side of the zooid in addition to the length and width? (Maybe this level of detail is not important, but it might be).
3: the edge of the avicularium that faces the zooids proximal end. (The orientation of the avicularia on the zooid might vary between zooids and species?) If the avicularia measurements are separated out then maybe it's better to orient these landmarks points along the the aviculariums own axis as this may be different than that of the zooid?
4: the distal end of the avicularium.
5: the end of the avicularim opposite point 2.
6: the midpoint on the distal end of the operculum.
7 and 8: the lateral corners of the operculum.
9: the midpoint on the proximal end of the autozooid.
10 and 22 mark the connection point to other zooids but in fossils where the junction point is eroded or the zooid is alone these landmarks might be used to span the autozooids width at its proximal edge.
11 and 12 are midpoints between 10 and 13.
13 and 19 mark the edge of this zooid that is closest to the junction point with other zooids (not necessarily the zooids widest part, but in a lot of the fossils, the zooid is alone or the connection points are very unclear, so the widest part might be a stand in in those cases).
14 is point on the zooid edge that is in line with the lower edge of the operculum. 
15 is at the distal right side junction with other zooids.
16 is the middle of the distal end
17 is the left side distal junction
18 is level with the operculums proximal edge.
19 is the left junction point with other zooids.
20 and 21 are midpoints between 19 and 22.
22 is the junction with other zooids on the left proximal end.

**Comment by lilysandstrom** [comment]
This was a figure I compared the Readme with to visualize some of the measurements: (From Emanuela and Lee Hsiangs 2022 paper "Changing allometric relationships among fossil and Recent populations in two colonial species".) It seems like those might be some of the traits we want to measure?
ZL = autozooid length
ZW = autozooid width
OrL = orifice length
OrW = orifice width
and separately,
AvL = avicularia length
AvW = avicularia width

![Microporella-agonistes-and-Microporella-speculum-and-the-modular-structures-measured](https://github.com/meghalithic/microporella/assets/117290965/79d50096-dd00-4648-88f8-47dea62c99a2)

The figure text is: Figure 1. Microporella agonistes and Microporella speculum and the modular structures measured. Panel (a) shows part of a colony of M. agonistes (Recent, Cook Strait KAH1204.04 shell 1 colony 23; SEM number: edm8185) and (b) part of M. speculum (Recent, Cook Strait KAH1206.20 shell 3 colony 5; SEM number: edm8152). Scale bars are 500 μm. Panel (c) shows the linear traits measured where ZL = autozooid length, ZW = autozooid width, OvL = ovicell length, OvW = ovicell width, OrL = orifice length, OrW = orifice width, AvL =avicularia length, AvW = avicularia width, DZL = distal autozooid (producing ovicell) length.

**Comment by meghalithic** [comment]
The readme file has been updated. We are using all the measurements from Di Martino & Liow 2022 as well as hopefully adding in measurements related to position on the autozooid based off work of Schack et al. 2020. 

We have decided to not use ML-morph for now as it seems most of the information we need are in the outputs of DeepBryo.
